/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IFont, IFontInterface } from "../IFont";

const _abi = [
  {
    inputs: [],
    name: "getFont",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IFont__factory {
  static readonly abi = _abi;
  static createInterface(): IFontInterface {
    return new utils.Interface(_abi) as IFontInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): IFont {
    return new Contract(address, _abi, signerOrProvider) as IFont;
  }
}
