"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.IInflateLib__factory = void 0;
const ethers_1 = require("ethers");
const _abi = [
    {
        inputs: [
            {
                internalType: "bytes",
                name: "source",
                type: "bytes",
            },
            {
                internalType: "uint256",
                name: "destlen",
                type: "uint256",
            },
        ],
        name: "puff",
        outputs: [
            {
                internalType: "enum IInflateLib.ErrorCode",
                name: "",
                type: "uint8",
            },
            {
                internalType: "bytes",
                name: "",
                type: "bytes",
            },
        ],
        stateMutability: "pure",
        type: "function",
    },
];
class IInflateLib__factory {
    static createInterface() {
        return new ethers_1.utils.Interface(_abi);
    }
    static connect(address, signerOrProvider) {
        return new ethers_1.Contract(address, _abi, signerOrProvider);
    }
}
exports.IInflateLib__factory = IInflateLib__factory;
IInflateLib__factory.abi = _abi;
