/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { ILandGranter, ILandGranterInterface } from "../ILandGranter";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "recipient",
        type: "address",
      },
    ],
    name: "grant",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class ILandGranter__factory {
  static readonly abi = _abi;
  static createInterface(): ILandGranterInterface {
    return new utils.Interface(_abi) as ILandGranterInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ILandGranter {
    return new Contract(address, _abi, signerOrProvider) as ILandGranter;
  }
}
