/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IRender, IRenderInterface } from "../IRender";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
      {
        internalType: "string[]",
        name: "palette",
        type: "string[]",
      },
      {
        internalType: "uint16",
        name: "numRows",
        type: "uint16",
      },
      {
        internalType: "uint16",
        name: "numCols",
        type: "uint16",
      },
    ],
    name: "renderSVG",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IRender__factory {
  static readonly abi = _abi;
  static createInterface(): IRenderInterface {
    return new utils.Interface(_abi) as IRenderInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IRender {
    return new Contract(address, _abi, signerOrProvider) as IRender;
  }
}
